[build]
target = "x86_64-unknown-linux-gnu"  # Default target, can be overridden

[target.x86_64-unknown-linux-gnu]
linker = "clang"

[target.x86_64-pc-windows-msvc]
linker = "clang"

[target.x86_64-apple-darwin]
linker = "clang"

[target.aarch64-apple-darwin]
linker = "clang"

# Python binding specific configuration
[env]
PYO3_PYTHON = "python3"
PYO3_USE_ABI3_FORWARD_COMPATIBILITY = "1"
